name: py310_openai
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2025.11.4=haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - pandoc=3.8=haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - winpty=0.4.3=4
  - vc14_runtime=14.44.35208=h4927774_10
  - vc=14.3=h2df5915_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - bzip2=1.0.8=h2bbff1b_6
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - tbb-devel=2022.0.0=h214f63a_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - mkl=2025.0.0=h5da7b33_930
  - python=3.10.19=h981015d_0
  - asttokens=3.0.0=py310haa95532_0
  - attrs=25.4.0=py310haa95532_0
  - babel=2.16.0=py310haa95532_0
  - certifi=2025.10.5=py310haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py310haa95532_0
  - debugpy=1.8.16=py310h885b0b7_0
  - decorator=5.2.1=py310haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - h11=0.16.0=py310haa95532_0
  - idna=3.7=py310haa95532_0
  - json5=0.9.25=py310haa95532_0
  - jupyterlab_widgets=3.0.15=py310haa95532_0
  - markupsafe=3.0.2=py310h827c3e9_0
  - mkl-service=2.5.2=py310h0b37514_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - overrides=7.4.0=py310haa95532_0
  - packaging=25.0=py310haa95532_1
  - pandocfilters=1.5.1=py310haa95532_0
  - parso=0.8.4=py310haa95532_0
  - platformdirs=4.3.7=py310haa95532_0
  - prometheus_client=0.21.1=py310haa95532_0
  - psutil=7.0.0=py310h02ab6af_0
  - pure_eval=0.2.3=py310haa95532_0
  - pycparser=2.23=py310haa95532_0
  - pygments=2.19.1=py310haa95532_0
  - python-fastjsonschema=2.20.0=py310haa95532_0
  - python-json-logger=3.2.1=py310haa95532_0
  - pywin32=311=py310h885b0b7_0
  - pywinpty=2.0.15=py310h72d21ff_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=27.1.0=py310h7149c55_0
  - regex=2025.9.1=py310h02ab6af_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rpds-py=0.22.3=py310h636fa0f_0
  - send2trash=1.8.2=py310haa95532_1
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sniffio=1.3.0=py310haa95532_0
  - soupsieve=2.5=py310haa95532_0
  - tomli=2.2.1=py310haa95532_0
  - tornado=6.5.1=py310h827c3e9_0
  - traitlets=5.14.3=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - wcwidth=0.2.13=py310haa95532_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=1.8.0=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - widgetsnbextension=4.0.13=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - anyio=4.10.0=py310haa95532_0
  - async-lru=2.0.5=py310haa95532_0
  - bleach=6.2.0=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_0
  - comm=0.2.1=py310haa95532_0
  - httpcore=1.0.9=py310haa95532_0
  - ipython_pygments_lexers=1.1.1=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.6=py310haa95532_0
  - jupyter_core=5.8.1=py310haa95532_0
  - jupyterlab_pygments=0.3.0=py310haa95532_0
  - matplotlib-inline=0.1.7=py310haa95532_0
  - pip=25.2=pyhc872135_1
  - prompt-toolkit=3.0.52=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - qtpy=2.4.3=py310haa95532_0
  - referencing=0.30.2=py310haa95532_0
  - rfc3339-validator=0.1.4=py310haa95532_0
  - stack_data=0.6.3=py310haa95532_0
  - terminado=0.18.1=py310haa95532_0
  - tinycss2=1.4.0=py310haa95532_0
  - typing-extensions=4.15.0=py310haa95532_0
  - argon2-cffi-bindings=25.1.0=py310h02ab6af_0
  - beautifulsoup4=4.13.5=py310haa95532_0
  - brotlicffi=1.0.9.2=py310h5da7b33_1
  - httpx=0.28.1=py310haa95532_1
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter_client=8.6.3=py310haa95532_0
  - jupyter_server_terminals=0.5.3=py310haa95532_0
  - mistune=3.1.2=py310haa95532_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - ipython=8.30.0=py310haa95532_0
  - jsonschema=4.25.0=py310haa95532_0
  - urllib3=2.5.0=py310haa95532_0
  - ipykernel=6.30.1=py310haa95532_0
  - ipywidgets=8.1.5=py310haa95532_0
  - jupyter_events=0.12.0=py310haa95532_0
  - nbformat=5.10.4=py310haa95532_0
  - requests=2.32.5=py310haa95532_0
  - jupyter_console=6.6.3=py310haa95532_0
  - nbclient=0.10.2=py310haa95532_0
  - qtconsole=5.7.0=py310haa95532_0
  - tiktoken=0.9.0=py310h8ecf97c_0
  - nbconvert-core=7.16.6=py310haa95532_0
  - jupyter_server=2.16.0=py310haa95532_0
  - nbconvert-pandoc=7.16.6=py310haa95532_0
  - jupyter-lsp=2.2.5=py310haa95532_0
  - jupyterlab_server=2.27.3=py310haa95532_0
  - nbconvert=7.16.6=py310haa95532_0
  - notebook-shim=0.2.4=py310haa95532_0
  - jupyterlab=4.4.7=py310haa95532_0
  - notebook=7.4.5=py310haa95532_0
  - jupyter=1.1.1=py310haa95532_0
  - mkl_fft=1.3.11=py310h5810407_1
  - mkl_random=1.2.8=py310h8683371_1
  - numpy=1.26.4=py310h12f7302_1
prefix: C:\Users\sw1\anaconda3\envs\py310_openai
